VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "your_box_name"
 # config.vm.network "public_network", ip: "10.x.x.x", netmask: "255.0.0.0", bridge:"en0: Wi-Fi (AirPort)"
  config.vm.network "private_network", ip: "192.168.10.5", netmask: "255.255.255.0", bridge:"en0: Wi-Fi (AirPort)"
  # config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.synced_folder "./html", "/var/www/html", :create => true, :owner  =>'root', :group => 'root'
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, "--nictype1", "virtio"]
    vb.customize ['modifyvm', :id, "--nictype2", "virtio"]
    vb.customize ["modifyvm", :id, "--natnet1", "192.168.156/24"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  config.vbguest.installer_arguments = "--nox11"

end
